


export default {
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_LARGE: 16,


    //blueGrey
    PRIMARY_COLOR: '#BDBDBD',
    PRIMARY_COLOR_LIGHT: '#E0E0E0',
    PRIMARY_COLOR_DARK: '#616161',

    ON_PRIMARY_COLOR: '#000000',
    ON_PRIMARY_COLOR_LIGHT: '#000000',
    ON_PRIMARY_COLOR_DARK: '#FFFFFF',

    BACKGROUND_COLOR: '#FFFFFF',
    ON_BACKGROUND_COLOR: '#000000'

}